name: build image
on:
  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  checkout:
    uses: meta/workflows/.forgejo/workflows/image-build.yml@master
    runs-on: docker
    secrets: inherit
    with:
      dockerfile: checkout/Dockerfile
      image: public/actions/checkout

  imagetags:
    uses: meta/workflows/.forgejo/workflows/image-build.yml@master
    runs-on: docker
    secrets: inherit
    with:
      dockerfile: imagetags/Dockerfile
      image: public/actions/imagetags

  dockerbuild:
    uses: meta/workflows/.forgejo/workflows/image-build.yml@master
    runs-on: docker
    secrets: inherit
    with:
      dockerfile: dockerbuild/Dockerfile
      image: public/actions/dockerbuild

  dockerlogin:
    uses: meta/workflows/.forgejo/workflows/image-build.yml@master
    runs-on: docker
    secrets: inherit
    with:
      dockerfile: dockerlogin/Dockerfile
      image: public/actions/dockerlogin
