name: check container build

on:
  pull_request:

permissions:
  contents: read

jobs:
  checkout:
    uses: meta/workflows/.forgejo/workflows/image-test.yml@master
    runs-on: docker
    with:
      dockerfile: checkout/Dockerfile

  imagetags:
    uses: meta/workflows/.forgejo/workflows/image-test.yml@master
    runs-on: docker
    with:
      dockerfile: imagetags/Dockerfile

  dockerbuild:
    uses: meta/workflows/.forgejo/workflows/image-test.yml@master
    runs-on: docker
    with:
      dockerfile: dockerbuild/Dockerfile

  dockerlogin:
    uses: meta/workflows/.forgejo/workflows/image-test.yml@master
    runs-on: docker
    with:
      dockerfile: dockerlogin/Dockerfile
