name: 'Image Tags'
description: 'Generate docker image tags based on git ref'
runs:
  using: 'docker'
  image: 'docker://forgejo.local:3000/public/actions/imagetags'
outputs:
  tags:
    description: 'Comma-separated list of docker image tags'
